---
all:
  children:
    openmanet_devices:
      hosts:
        gateway:
          ansible_host: 192.168.70.92
          ansible_user: root
          ansible_password: mV2MDPJ6I1RfQG4*
          # Or use ansible_ssh_private_key_file: /path/to/key
          
        mesh_point:
          ansible_host: openmanet-point.lan
          ansible_user: root
          ansible_password: mV2MDPJ6I1RfQG4*
          # Or use ansible_ssh_private_key_file: /path/to/key
          
      vars:
        # Default variables for all devices
        device_user: root
        ansible_python_interpreter: auto_silent

